"""Reference torture-corpus generator (spec 002 US1, T024).

Implements the contract `tools/refimpl/test_torture.py` (T013) already pins: written
from `specs/002-trunk-link-layer/contracts/link-python.md`'s "torture.py" section and
`research.md` R-08, using the `Element` shape and `frames` reading recorded in
docs/OPEN-QUESTIONS.md ("T013: torture-corpus `Element` shape and `frames` parameter
meaning", 2026-08-30): a flat one-corruption-per-element record (`stream`, `expected`,
`expected_discards`, `recipe`), with `frames` counting delivered/valid frames only —
corrupted elements (>= `per_class` per class) are additional to that floor.

`corpus(seed)` first yields `frames` valid elements (one encoded frame each), then, for
each of the eight corruption classes, `per_class` corrupted elements. Every corrupted
stream is self-checked against the reference `Deframer` before being emitted: if the
corruption still parses as a frame (CRC-lucky), it is discarded and regenerated by
drawing further from the same seeded `random.Random` (the "next sub-seed" of R-08) — so
`corpus(seed)` never emits an accepted corruption, by construction, and stays
deterministic because everything is drawn from one seeded generator, never wall-clock or
set/dict iteration order (CLAUDE.md rule 3; R-08).
"""
from __future__ import annotations

import pathlib
import random
import sys
from dataclasses import dataclass
from typing import Iterator, List

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from _gen import P  # noqa: E402
from omgp_link import _MAX_UNSTUFFED, Deframer, Frame, encode_frame  # noqa: E402

_G = P()
FLAG = _G.TRUNK_flag_byte
ESC = _G.TRUNK_escape_byte
XOR = _G.TRUNK_escape_xor
MAX_PAYLOAD = _G.LIMIT_max_l3_payload

_RESERVED_DST = 0xFF
_GOOD_ESCAPES = (FLAG ^ XOR, ESC ^ XOR)

CLASSES = ("flip", "drop", "insert", "truncate", "flag", "bad_escape", "garbage", "overlength")


@dataclass(frozen=True)
class Element:
    stream: bytes
    expected: List[Frame]
    expected_discards: int
    recipe: str


def _random_valid_frame(rng: random.Random) -> Frame:
    dst = rng.randrange(0, _RESERVED_DST)  # excludes the reserved broadcast address
    src = rng.randrange(0, 256)
    response = rng.getrandbits(1) == 1
    retry = rng.getrandbits(1) == 1
    seq = rng.randrange(0, 16)
    length = rng.randrange(0, MAX_PAYLOAD + 1)
    payload = bytes(rng.randrange(0, 256) for _ in range(length))
    return Frame(dst=dst, src=src, response=response, retry=retry, seq=seq, payload=payload)


def _valid_element(rng: random.Random) -> Element:
    frame = _random_valid_frame(rng)
    return Element(stream=encode_frame(frame), expected=[frame], expected_discards=0, recipe="valid")


def _random_bad_escape_byte(rng: random.Random) -> int:
    b = rng.randrange(256)
    while b in _GOOD_ESCAPES:
        b = rng.randrange(256)
    return b


def _corrupt_flip(rng: random.Random, body: bytearray) -> bool:
    if not body:
        return False
    i = rng.randrange(len(body))
    bit = 1 << rng.randrange(8)
    body[i] ^= bit
    return True


def _corrupt_drop(rng: random.Random, body: bytearray) -> bool:
    if not body:
        return False
    del body[rng.randrange(len(body))]
    return True


def _corrupt_insert(rng: random.Random, body: bytearray) -> bool:
    i = rng.randrange(len(body) + 1)
    b = rng.randrange(256)
    while b == FLAG:
        b = rng.randrange(256)
    body.insert(i, b)
    return True


def _corrupt_truncate(rng: random.Random, body: bytearray) -> bool:
    if len(body) < 2:
        return False
    cut = rng.randrange(1, len(body))
    del body[cut:]
    return True


def _corrupt_flag(rng: random.Random, body: bytearray) -> bool:
    if not body:
        return False
    body.insert(rng.randrange(len(body) + 1), FLAG)
    return True


def _corrupt_bad_escape(rng: random.Random, body: bytearray) -> bool:
    esc_positions = [i for i, b in enumerate(body) if b == ESC]
    if esc_positions and esc_positions[-1] + 1 < len(body):
        i = rng.choice([p for p in esc_positions if p + 1 < len(body)])
        body[i + 1] = _random_bad_escape_byte(rng)
        return True
    # Fallback (no ESC already in the body): insert the pair ADJACENTLY so the element
    # always contains a literal invalid escape sequence. Independent insert positions
    # (review on PR #100, finding 1) left ~0.6% of elements (6/1000 at seed 20260830,
    # measured pre-fix) whose only ESC happened to precede a valid escape byte —
    # discarding as BadLength/BadCrc while labelled bad_escape.
    i = rng.randrange(len(body) + 1)
    body[i:i] = bytes([ESC, _random_bad_escape_byte(rng)])
    return True


def _corrupt_garbage(rng: random.Random, body: bytearray) -> bool:
    n = rng.randrange(1, MAX_PAYLOAD)
    body[:] = bytes(0x00 if b == FLAG else b for b in (rng.randrange(0, 256) for _ in range(n)))
    return True


def _corrupt_overlength(rng: random.Random, body: bytearray) -> bool:
    # _MAX_UNSTUFFED (4-byte header + 64-byte max payload + 2-byte CRC = 70) unstuffed
    # bytes is the cap (trunk §4; C++ parity in test_link.py's TooLong test). Two
    # variants, half each (review on PR #100, finding 2):
    # - plain: no FLAG/ESC, so unstuffed length equals raw length — deterministic abort;
    # - escaped boundary: exactly the cap in plain bytes, then a VALID escape pair, so
    #   the first over-cap byte arrives via the Escaped state — the 1ad9ad3 bug class
    #   (PR #99: TooLong abort clobbered by the Escaped->InFrame transition), which the
    #   corpus could not previously express because it excluded ESC entirely. The pair is
    #   followed by 1-7 more plain bytes (red-team round 10 on #121): with the ESC pair
    #   LAST, 496 elements reached the abort line and zero could observe the clobbered
    #   post-abort state — the regression only shows once further bytes arrive.
    if rng.getrandbits(1):
        extra = rng.randrange(1, MAX_PAYLOAD)
        body[:] = bytes(
            0x00 if b in (FLAG, ESC) else b
            for b in (rng.randrange(0, 256) for _ in range(_MAX_UNSTUFFED + extra))
        )
    else:
        plain = bytes(
            0x00 if b in (FLAG, ESC) else b
            for b in (rng.randrange(0, 256) for _ in range(_MAX_UNSTUFFED))
        )
        tail = bytes(
            0x00 if b in (FLAG, ESC) else b
            for b in (rng.randrange(0, 256) for _ in range(rng.randrange(1, 8)))
        )
        body[:] = plain + bytes([ESC, rng.choice(_GOOD_ESCAPES)]) + tail
    return True


_CORRUPTORS = {
    "flip": _corrupt_flip,
    "drop": _corrupt_drop,
    "insert": _corrupt_insert,
    "truncate": _corrupt_truncate,
    "flag": _corrupt_flag,
    "bad_escape": _corrupt_bad_escape,
    "garbage": _corrupt_garbage,
    "overlength": _corrupt_overlength,
}


def _corrupted_element(rng: random.Random, corruption_class: str) -> Element | None:
    base = _random_valid_frame(rng)
    body = bytearray(encode_frame(base)[1:-1])
    if not _CORRUPTORS[corruption_class](rng, body):
        return None
    stream = bytes([FLAG]) + bytes(body) + bytes([FLAG])
    check = Deframer()
    delivered = check.feed_bytes(stream)
    if delivered:
        return None  # CRC-lucky: regenerate with the next sub-seed
    discards = sum(v for k, v in check.stats.items() if k != "delivered")
    return Element(stream=stream, expected=[], expected_discards=discards, recipe=corruption_class)


def corpus(seed: int, frames: int = 10_000, per_class: int = 1_000) -> Iterator[Element]:
    rng = random.Random(seed)
    for _ in range(frames):
        yield _valid_element(rng)
    for corruption_class in CLASSES:
        emitted = 0
        while emitted < per_class:
            element = _corrupted_element(rng, corruption_class)
            if element is not None:
                yield element
                emitted += 1
